### PR TITLE
Added info about running Moodle behind Nginx

### PR DESCRIPTION
**Pull request by tmdoit**
**Description of the change**

Running Moodle behind reverse proxy (Nginx)

**Benefits**

People will run succesfully Moodle behind Nginx.

**Possible drawbacks**

Don't know

**Applicable issues**

https://github.com/bitnami/bitnami-docker-moodle/issues/68

**Additional information**

None

### CODE REVIEW

**Comment by armenic** [comment]
I am voting for this pull request to be added into repo. @tmdoit simple instruction about `hostname` directive saved me from switching to the cloud instead of using my own garage servers :) Excellent work @tmdoit, keep up the great work!

**Comment by marcosbc** [comment]
Hi, isn't it enough to configure `MOODLE_SITENAME`? If so, it is probably better to add `MOODLE_SITENAME` in the list of parameters, and mention that if not properly set up, it may cause issues when accessing to the site.

**Comment by tmdoit** [comment]
@marcosbc I can't tell, didn't test it with this parameter.

**Comment by marcosbc** [comment]
@tmdoit Could you check it with that parameter? It is less hacky and also more standarized. Thanks!

**Comment by tmdoit** [comment]
I will check it no sooner than in a month.

**Comment by marcosbc** [comment]
Closing as this is more than a year old. The `MOODLE_SITE_NAME` is used for this purpose. Also, note we recently refactored the container so it may work now if it didn't before. For more details see: https://github.com/bitnami/bitnami-docker-moodle#390-debian-10-r17

**Pull request closed without merging**
